name: Deploy BrainFlow Java code to Clojars to be used in Clojure

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
     
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
       
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@12.1
      with:
        cli: latest
    
    - name: Run tests (optional)
      run: clojure -M:test -m clojure.test.runner
      continue-on-error: true  # Don't fail deployment if tests fail
       
    - name: Build lightweight jar (source code only)
      run: clojure -T:build jar
     
    - name: Check jar size
      run: |
        ls -lh target/*.jar
        echo "Jar size should be under 1MB for Clojars compatibility"
     
    - name: Deploy to Clojars
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
      run: clojure -T:build deploy